name: fashion_ecommerce_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  animate_do: ^3.0.2
  advance_notification: ^1.0.6
  badges: ^2.0.3
  line_icons: ^2.0.1
  bottom_bar_matu: ^1.3.0
  image_picker: ^1.0.0
  cloud_firestore: ^4.8.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  provider: ^6.0.5
  font_awesome_flutter: ^9.2.0
  fluttertoast: ^8.2.2
  speech_to_text: ^6.1.0
  avatar_glow: ^2.0.2
  flutter_stripe: ^9.1.1
  http: ^0.13.6
  firebase_storage: ^11.2.5
  camera: ^0.10.5+2
  mailer: ^6.0.1
  google_sign_in: ^6.1.4
  tflite: ^1.1.2
  image: ^3.0.0
  tflite_flutter: ^0.10.1
  image_pixels: ^3.0.0
  get: ^4.6.5
  image_compare: ^1.1.2
  path_provider: ^2.1.0
  flutter_email_sender: ^5.1.0
  firebase_analytics: ^10.4.5
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  vector_math: ^2.1.4
  google_fonts: ^4.0.4
  flutter_spinkit: ^5.2.0
  device_info_plus: ^9.0.3
  shared_preferences: ^2.2.1
  video_player: ^2.7.1
  flutter_launcher_icons: ^0.9.0
  

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/
    - assets/videos/demovideo.mp4
  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
        - asset: assets/fonts/AlegreyaSans-Medium.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # Replace with your icon's path


  